### ISSUE TITLE
Extension of SMOTE function

### ISSUE THREAD

**Issue by ramonVDAKKER** [devolksbank/dvb.datascience#12]
If I am correct dvb.datascience.transform.smote  is able to oversample, using SMOTE, the minority class. It would also be helpful if once could simultaneously undersample the majority class.  (This is/might be useful in situations where one has to deal with extremely imbalanced classes (e.g. fraud detection).)

**Comment by mrijken** [comment]
The constructor of SMOTESampler will pass all kwargs to SMOTE, so all  arguments of SMOTE can be used. For example:

    ratio (default: 'auto'):
        - If ``str``, has to be one of: (i) ``'minority'``: resample the
          minority class; (ii) ``'majority'``: resample the majority class,
          (iii) ``'not minority'``: resample all classes apart of the minority
          class, (iv) ``'all'``: resample all classes, and (v) ``'auto'``:
          correspond to ``'all'`` with for over-sampling methods and ``'not
          minority'`` for under-sampling methods. The classes targeted will be
          over-sampled or under-sampled to achieve an equal number of sample
          with the majority or minority class.
        - If ``dict``, the keys correspond to the targeted classes. The values
          correspond to the desired number of samples.
        - If callable, function taking ``y`` and returns a ``dict``. The keys
          correspond to the targeted classes. The values correspond to the
          desired number of samples.

I will add this explicit in the docs.
